monogatari.script({
    //scene rumah
    'PartSix': [
        "wait 1000",
        "show scene langitMalam with fadeOut duration 1s",
        "wait 1000",
        "Sepulangnya kerumah.",
        "show scene dalamRumah with fadeIn duration 1s",
        "play sound door_open",
        "play music bgm04 with loop",
        "arif Halo..",
        "arif Kenapa didalam sepi ya?",
        "play sound door_close",
        "arif Ada orang di rumah?",
        "show character kinan piyamaSenang with fadeIn",
        "play voice 133",
        "kinan Kakak.",
        //"show character  with fadeIn",
        "play voice 134",
        "kinan Selamat malam kakak.", //hmm rasa aneh
        "show character kinan piyamaKaget",
        "play voice 135",
        "kinan Kakak kok baru pulang sih?",
        "arif Tadi kakak pergi ke Mall.",
        "show character kinan piyamaSedih",
        "play voice 136",
        "kinan Ih kakak ke Mall gak ngajak Kinan.",
        //"show character  with fadeIn",
        "play voice 137",
        "kinan Kinan sendirian dirumah tau.",
        "arif Hehehe, tadi kakak pulang sekolah "+
        "langsung diajakin sama Roy jalan ke Mall.",
        //"show character  with fadeIn",
        "play voice 138",
        "kinan Hmm..",
        "arif Heheh maaf ya, kaka ngga ngabarin.",
        //"show character  with fadeIn",
        "play voice 139",
        "kinan Kaka jahat, gak mau tau kaka harus buatin kinan makan malam.",
        "arif Ya iya, kakak buatin tapi maafin kakak ya.",
        "show character kinan piyamaNormal",
        "play voice 140",
        "kinan mm..",
        "Kinan menganggukkan kepalanya secara vertikal",
        "hide character kinan with fadeOut duration 1s",
        "Setelah itu kami pun makan malam bersama.",
        "show character kinan piyamaBicara with fadeIn duration 1s",
        "play voice 141",
        "kinan Akhirnya kenyang juga.",
        "show character kinan piyamaSenang",
        "play voice 142",
        "kinan Masakan kakak emang enak.",
        "arif Hehehe, Terima kasih kembali",
        //"show character  with fadeIn",
        "play voice 143",
        "kinan Sama - sama kakak.",
        "arif Kinan tidur lagi ya..",//knpa tidur lagi?
        "show character kinan piyamaBicara",
        "play voice 144",
        "kinan Gak mau sebelum kakak bacain cerita.",
        "arif Haaa...",
        "show character kinan piyamaNormal",
        "play voice 145",
        "kinan Harus cerita baru Kinan mau tidur.",
        "arif Kakak ga tau mau cerita apa.",
        "show character kinan piyamaBicara",
        "play voice 146",
        "kinan Terserah kakak, yang penting kakak "+
        "ceritain sesuatu terus baru kinan mau tidur.",
        "arif Hmmm... ya udah, kinan ke kamar dulu, "+
        "nanti kaka ceritain sesuatu.",
        "show character kinan piyamaSenang",
        "play voice 147",
        "kinan Yeeee, sayang kakak.",
        "show background dalamRumah",
        "show scene dalamRumah with fadeOut duration 1s",
        "wait 1000",
        "show scene kamarKinanMalam with fadeIn duration 1s",
        //Kamar Kinan
        "play sound door_open",
        "arif Ayok baring dikasur dulu.",
        "show character kinan piyamaSenang with fadeIn",
        "play voice 148",
        "kinan Oke kaka.",
        //"show character  with fadeIn",
        "hide character kinan with fadeOutDown",
        "play voice 149",
        "kinan Ceritanya yang bagus ya.",
        "arif Iya.",
        "arif Kakak mulai nih.",
        //"show character  with fadeIn",
        "play voice 150",
        "kinan Siap.",
        "arif Pada suatu hari ....",
        "............",
        ".......",
        "...",
        "arif Sudah tidur ternyata",
        "arif Aku harus belajar nih.",
        //sfx pintu tutup
        "show background kamarKinanMalam",
        "show scene kamarKinanMalam with fadeOut duration 1s",
        "wait 1000",
        "show scene langitMalam with fadeIn duration 1s",
        "arif Banyak pelajaran yang diambil tadi disekolah.",
        "arif Lumayan buat nambah ilmu.",
        "arif Tentang rumah kaca, kenapa gak kuterapin juga pada diriku ya.",
        "arif Mana tau membantu juga.",
        "arif Tapi ngelakuin apa ya?",
        "............",
        ".......",
        "...",
        "stop music bgm04 with fade 3",
        "show background langitMalam",
        "show scene langitMalam with fadeOut duration 1s",
        "wait 1000",
        "show scene #000000",
        "Semenjak kejadian naiknya suhu di kota sejuk, "+
        "Banyak para siswa sadar betapa bahayanya asap kendaraan "+
        "bermotor yang asapnya sangat berbahaya dan berpotensi "+
        "terjadinya efek rumah kaca, Roy yang selalu ditegur nadia dan arif " +
        "pun sekarang sudah berjalan kaki ke sekolah.",
        "show scene langitSiang with fadeIn duration 1s",
        "3 bulan lebih  kemudian mereka jalani untuk mengurangi gas rumah kaca",
        "Pada suatu hari di sekolah",
        "show background langitSiang",
        "show scene langitSiang with fadeOut duration 1s",
        "wait 1000",
        "show scene kelasSiang with fadeIn duration 1s",
        "arif Udah 3 bulan nih banyak siswa disekolah kita ga bawa motor ke sekolah.",
        "show character nadia sekolahSenang at right with fadeIn",
        "show character roy senyum at left with fadeIn",
        "play voice 151",
        "nadia Iya nih, termasuk Roy juga.",
        //"show character  with fadeIn",
        "play voice 152",
        "roy Hehehe...",
        "show character roy bicara at left",
        "play voice 153",
        "roy Ngomongin itu, suhu sekarang dikota kita udah lumayan loh.",
        //"show character  with fadeIn",
        "play voice 154",
        "roy Yang sebelumnya 35 derajat sekarang udah jadi 29 derajat.",
        "show character nadia sekolahSenyum at right",
        "play voice 155",
        "nadia Nah kan, lumayan sejukkan jadinya.", //masuk musim dingin paling ini
        "show character nadia sekolahSenang at right",
        "play voice 156",
        "nadia Walaupun itu hal yang sepele, "+
        "tetapi efeknya akan kita rasakan pada masa yang akan datang.",
        "arif Untung ditegur terus sama Nadia, "+
        "kalo ga dah pasti bawa motor terus ke sekolah.",
        "arif Ngga disekolah aja mungkin, di luar juga kan.",
        "show character roy tertawaSenang at left",
        "play voice 157",
        "roy He he he...", // (Ketawa kecil)
        "show background kelasSiang",
        "show scene kelasSiang with fadeOut duration 1s",
        "wait 1000",
        "show scene langitSiang with fadeIn duration 1s",
        "Hal yang ada disekitar kita walaupun itu hal kecil bisa mendatangkan suatu efek " +
        "kepada kita baik efek buruk maupun efek baik.",
        "Berkendara motor boleh, tapi ingat semakin banyak penggunaan kendaraan bermotor " +
        "maka sedikit demi sedikit pembakaran bahan bakar kendaraan bermotor ini menghasilkan " +
        "gas rumah kaca berupa karbonmonoksida(CO), karbondioksida(CO2), dan uap air(H2O).",
        "inilah yang akan membuat suhu bumi menjadi panas " +
        "jadi mari sama sama kita basmi dampak efek rumah kaca.",
        "show scene langitSiang with fadeOut duration 2s",
        "wait 3000",
        "show video credit immersive with close",
        "end"
    ]
});